spring:

  application:
    name: companies-crud
  datasource:
    username: ${db.username}
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    url: ${db.url}
    password: ${db.password}
  profile: default
  config:
        import: "optional:configserver:http://localhost:7777"

server:
  servlet:
    context-path: /companies-crud
  port: 8081
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
